const { forwardTo } = require("prisma-binding");
const { hasPermission } = require("../utils");

const Query = {
  // async items(parent, args, ctx, info) {
  // Prisma knows to wait for a promise to resolve
  // if a promise is returned, but we are returning
  // the actual data anyways to be able to debug in
  // here.
  //   const items = await ctx.db.query.items();
  //   return items;
  // }

  // To forward resolvers to those generated by prisma,
  // we can use:
  items: forwardTo("db"),
  item: forwardTo("db"),
  itemsConnection: forwardTo("db"),
  me(parent, args, ctx, info) {
    // Check if there is a userId
    if (!ctx.request.userId) {
      return null;
    }
    return ctx.db.query.user(
      {
        where: { id: ctx.request.userId }
      },
      info
    );
  },
  async users(parent, args, ctx, info) {
    // 1. Check if the user is logged in
    if (!ctx.request.userId) {
      throw new Error("You must be logged in!");
    }
    // 2. Check if the user has the permissions to query
    // all user permissions
    hasPermission(ctx.request.user, ["ADMIN", "PERMISSIONUPDATE"]);

    // 3. If they do, query all user permissions
    return ctx.db.query.users({}, info);
  },

  async order(parent, args, ctx, info) {
    // 1. Make sure they are logged in
    if (!ctx.request.userId) {
      throw new Error("You aren't logged in!");
    }

    // 2. Query the current order
    const order = await ctx.db.query.order(
      {
        where: { id: args.id }
      },
      info
    );

    // 3. Check if they have the permission to see this order
    const ownsOrder = order.user.id === ctx.request.userId;
    const hasPermissionToSeeOrder = ctx.request.user.permissions.includes(
      "ADMIN"
    );
    if (!ownsOrder || !hasPermissionToSeeOrder) {
      throw new Error("You can't see this order, buddd!");
    }

    // 4. Return the order
    return order;
  },

  async orders(parent, args, ctx, info) {
    const userId = ctx.request.userId;
    // 1. Make sure they are logged in
    if (!ctx.request.userId) {
      throw new Error("You aren't logged in!");
    }

    // 2. Query the orders that user has made
    return await ctx.db.query.orders(
      {
        where: { user: { id: userId } }
      },
      info
    );
  }

  // Later, you can go in and write custom resolvers
  // that do what you need them to do.
};

module.exports = Query;
